// @ts-check

//
// This is only a placeholder file for typescript and eslint
//
// The real content for this file will be generated by runtime-loader.js
// 

/** @type {{[publicPath: string]: string[]}} */
var tags = {};
module.exports = tags;