// @ts-check

//
// This is only a placeholder file for typescript and eslint
//
// The real content for this file will be generated by runtime-loader.js
// 

/** 
 * All tags from all favicons compilations
 * 
 * @type {{[publicPath: string]: string[]}} 
 * 
 * @example 
```js
{ 'assets/': [ '<link rel="icon" href="assets/favicon.png">' ] }
```
 */
var tags = {};
module.exports = tags;