blank_issues_enabled: false
contact_links:
  - name: Open Collective
    url: https://opencollective.com/html-webpack-plugin/donate
    about: Want to give something back? Please consider supporting us via Open Collective.